In [1]:
import numpy as np

In [2]:
v = np.array([1,2,3])

In [3]:
v

array([1, 2, 3])

In [4]:
v*v


array([1, 4, 9])

In [5]:
v**2+1

array([ 2,  5, 10])

In [6]:
1/v

array([1.        , 0.5       , 0.33333333])

In [7]:
#v[3]

IndexError: ignored

In [8]:
v[-2]

2

In [9]:
len(v)

3

In [10]:
v.shape

(3,)

In [11]:
A = np.random.rand(5,5) #matrix

In [12]:
print(A)



[[0.18901525 0.36444411 0.10202612 0.83594828 0.74761673]
 [0.82185998 0.96991599 0.81023099 0.41323705 0.84373201]
 [0.67326596 0.43729993 0.85534377 0.58744032 0.02371202]
 [0.8523337  0.69636817 0.4960165  0.16819739 0.69511858]
 [0.21613582 0.58745444 0.27596181 0.4638518  0.24329281]]


In [13]:
A[2,3]#faster than A[2][3]

0.587440319639063

In [14]:
A[2:5,3]

array([0.58744032, 0.16819739, 0.4638518 ])

In [15]:
A[:,1]

array([0.36444411, 0.96991599, 0.43729993, 0.69636817, 0.58745444])

In [16]:
A[:-1,::]

array([[0.18901525, 0.36444411, 0.10202612, 0.83594828, 0.74761673],
       [0.82185998, 0.96991599, 0.81023099, 0.41323705, 0.84373201],
       [0.67326596, 0.43729993, 0.85534377, 0.58744032, 0.02371202],
       [0.8523337 , 0.69636817, 0.4960165 , 0.16819739, 0.69511858]])

In [17]:
A[:-1,::][0,0]=10


In [18]:
A


array([[10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673],
       [ 0.82185998,  0.96991599,  0.81023099,  0.41323705,  0.84373201],
       [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202],
       [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858],
       [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281]])

In [19]:
A+7

array([[17.        ,  7.36444411,  7.10202612,  7.83594828,  7.74761673],
       [ 7.82185998,  7.96991599,  7.81023099,  7.41323705,  7.84373201],
       [ 7.67326596,  7.43729993,  7.85534377,  7.58744032,  7.02371202],
       [ 7.8523337 ,  7.69636817,  7.4960165 ,  7.16819739,  7.69511858],
       [ 7.21613582,  7.58745444,  7.27596181,  7.4638518 ,  7.24329281]])

In [20]:
B=A[2:4,2:3]

In [21]:
B


array([[0.85534377],
       [0.4960165 ]])

In [22]:
B=A[2:4,2]

In [23]:
B


array([0.85534377, 0.4960165 ])

In [24]:
np.where(A>2)

(array([0]), array([0]))

In [25]:
r,c = np.where(A>2)

In [26]:
r[0],c[0]

(0, 0)

In [27]:
print(r)

[0]


In [28]:
A


array([[10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673],
       [ 0.82185998,  0.96991599,  0.81023099,  0.41323705,  0.84373201],
       [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202],
       [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858],
       [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281]])

In [29]:
A>2

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [30]:
A[[3,2,1],:]

array([[0.8523337 , 0.69636817, 0.4960165 , 0.16819739, 0.69511858],
       [0.67326596, 0.43729993, 0.85534377, 0.58744032, 0.02371202],
       [0.82185998, 0.96991599, 0.81023099, 0.41323705, 0.84373201]])

In [31]:
v=A[3,:]

In [32]:
v


array([0.8523337 , 0.69636817, 0.4960165 , 0.16819739, 0.69511858])

In [33]:
v[np.where(v<7)]

array([0.8523337 , 0.69636817, 0.4960165 , 0.16819739, 0.69511858])

In [34]:
np.clip(v,1,2)

array([1., 1., 1., 1., 1.])

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
type((3,5))

tuple

In [39]:
np.zeros((3,5)).copy

<function ndarray.copy>

In [40]:
B=A

In [41]:
B[1,1]=0

In [42]:
A


array([[10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673],
       [ 0.82185998,  0.        ,  0.81023099,  0.41323705,  0.84373201],
       [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202],
       [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858],
       [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281]])

In [43]:
A.reshape((25))

array([10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673,
        0.82185998,  0.        ,  0.81023099,  0.41323705,  0.84373201,
        0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202,
        0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858,
        0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281])

In [44]:
A

array([[10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673],
       [ 0.82185998,  0.        ,  0.81023099,  0.41323705,  0.84373201],
       [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202],
       [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858],
       [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281]])

In [45]:
A.reshape((1,5,5))

array([[[10.        ,  0.36444411,  0.10202612,  0.83594828,
          0.74761673],
        [ 0.82185998,  0.        ,  0.81023099,  0.41323705,
          0.84373201],
        [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,
          0.02371202],
        [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,
          0.69511858],
        [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,
          0.24329281]]])


LINEAR ALG



In [46]:
A.T


array([[10.        ,  0.82185998,  0.67326596,  0.8523337 ,  0.21613582],
       [ 0.36444411,  0.        ,  0.43729993,  0.69636817,  0.58745444],
       [ 0.10202612,  0.81023099,  0.85534377,  0.4960165 ,  0.27596181],
       [ 0.83594828,  0.41323705,  0.58744032,  0.16819739,  0.4638518 ],
       [ 0.74761673,  0.84373201,  0.02371202,  0.69511858,  0.24329281]])

In [47]:
np.transpose(A)

array([[10.        ,  0.82185998,  0.67326596,  0.8523337 ,  0.21613582],
       [ 0.36444411,  0.        ,  0.43729993,  0.69636817,  0.58745444],
       [ 0.10202612,  0.81023099,  0.85534377,  0.4960165 ,  0.27596181],
       [ 0.83594828,  0.41323705,  0.58744032,  0.16819739,  0.4638518 ],
       [ 0.74761673,  0.84373201,  0.02371202,  0.69511858,  0.24329281]])

In [48]:
A


array([[10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673],
       [ 0.82185998,  0.        ,  0.81023099,  0.41323705,  0.84373201],
       [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202],
       [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858],
       [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281]])

In [49]:
?np.transpose

In [50]:
A.sum()

22.21088829056458

In [51]:
A.sum(axis=1)

array([12.05003524,  2.88906003,  2.57706199,  2.90803434,  1.78669668])

In [52]:
A.sum(axis=0)

array([12.56359546,  2.08556665,  2.53957919,  2.46867484,  2.55347215])

In [53]:
np.sum(A,axis=1)

array([12.05003524,  2.88906003,  2.57706199,  2.90803434,  1.78669668])

In [54]:
np.argmax(A)

0

In [55]:
np.max(A)

10.0

In [56]:
A


array([[10.        ,  0.36444411,  0.10202612,  0.83594828,  0.74761673],
       [ 0.82185998,  0.        ,  0.81023099,  0.41323705,  0.84373201],
       [ 0.67326596,  0.43729993,  0.85534377,  0.58744032,  0.02371202],
       [ 0.8523337 ,  0.69636817,  0.4960165 ,  0.16819739,  0.69511858],
       [ 0.21613582,  0.58745444,  0.27596181,  0.4638518 ,  0.24329281]])

In [57]:
A[4,4]=77

In [58]:
idx = np.argmax(A,axis=1)
idx

array([0, 4, 2, 0, 4])

In [59]:
A

array([[1.00000000e+01, 3.64444108e-01, 1.02026117e-01, 8.35948282e-01,
        7.47616731e-01],
       [8.21859981e-01, 0.00000000e+00, 8.10230995e-01, 4.13237047e-01,
        8.43732010e-01],
       [6.73265957e-01, 4.37299931e-01, 8.55343769e-01, 5.87440320e-01,
        2.37120169e-02],
       [8.52333702e-01, 6.96368165e-01, 4.96016498e-01, 1.68197395e-01,
        6.95118581e-01],
       [2.16135815e-01, 5.87454443e-01, 2.75961814e-01, 4.63851800e-01,
        7.70000000e+01]])

In [60]:
i=0
for j in idx:
    print(A[i,j])
    i+=1

10.0
0.8437320104124373
0.8553437693174805
0.8523337019062103
77.0


In [61]:
import numpy.linalg as la

In [62]:
b=np.random.rand(A.shape[0])
x1 = la.solve(A,b)
x1

array([ 0.13488599, -0.14304196,  1.21768659, -1.40504617,  0.01164714])

In [63]:
A*x1-b

array([[ 1.0937333 , -0.57880555, -0.12046212, -1.56566762, -0.51754727],
       [-0.1442692 , -0.52667475,  0.74190947, -0.97173882, -0.5164278 ],
       [-0.16431245, -0.58922699,  0.79684269, -1.21650246, -0.52597869],
       [-0.14015872, -0.62628462,  0.35929469, -0.62744679, -0.51815872],
       [-0.2259729 , -0.61070538,  0.09133705, -1.04285488,  0.37057514]])

In [64]:
A@x1-b

array([-1.11022302e-16,  0.00000000e+00, -2.77555756e-17,  0.00000000e+00,
        1.11022302e-16])

In [65]:
A.dot(x1)

array([0.25512659, 0.52667475, 0.24469795, 0.39112169, 0.52625487])

In [66]:
A@x1-b

array([-1.11022302e-16,  0.00000000e+00, -2.77555756e-17,  0.00000000e+00,
        1.11022302e-16])

In [67]:
r = A@x1 - b

In [68]:
la.norm(r)

1.594436429147036e-16

In [69]:
b,la.norm(b)

(array([0.25512659, 0.52667475, 0.24469795, 0.39112169, 0.52625487]),
 0.9122901503080041)

In [70]:
(b**2).sum()**0.5

0.9122901503080041

In [71]:
b,la.norm(b, np.inf)

(array([0.25512659, 0.52667475, 0.24469795, 0.39112169, 0.52625487]),
 0.5266747502431306)

In [72]:
-b,la.norm(-b, 1)

(array([-0.25512659, -0.52667475, -0.24469795, -0.39112169, -0.52625487]),
 1.9438758483775518)

In [73]:
la.inv(A) @ A

array([[ 1.00000000e+00,  1.14456462e-17,  5.24510401e-17,
         3.37745217e-17,  1.19002030e-15],
       [ 2.61656318e-16,  1.00000000e+00, -3.76009158e-17,
        -8.02608623e-17, -2.46851151e-15],
       [ 3.15205324e-18,  2.08136798e-16,  1.00000000e+00,
         1.62268666e-16,  6.45317133e-15],
       [-3.98355985e-16, -3.71028481e-16, -1.16288178e-15,
         1.00000000e+00, -1.52100554e-14],
       [ 1.46141014e-18,  6.65186888e-19,  3.45302180e-18,
         1.21442819e-18,  1.00000000e+00]])

In [74]:
delta = la.inv(A) @ A - np.eye(A.shape[0])

In [75]:
la.norm(delta)

1.68182114372715e-14

In [76]:
la.norm(delta,1)

2.5321758578833453e-14

In [77]:





def norm1(A):
    #вернуть макс столбцовую норму
    return la.norm(delta,1)

In [78]:
(norm1(A),la.norm(A,1))

(2.5321758578833453e-14, 79.31017933925652)

In [79]:
##Домножитьвсе элементы матрицв кроме крайних строк и столбцов на -1

In [80]:
##проверить что функция нормы не перестаоа работать


In [81]:
#la.eig(A)[0]

In [82]:
la.eigvals(A)

array([77.0134427 +0.j        , 10.11812769+0.j        ,
        1.46961288+0.j        , -0.28882105+0.07989857j,
       -0.28882105-0.07989857j])

# Написать функцию возвращающуб столбцовую норму матрицы

решение



In [108]:
A = np.random.randint(10, size = (4,3))

In [110]:
print(A)

[[2 4 7]
 [7 9 0]
 [6 7 2]
 [0 6 5]]


In [111]:
la.norm(A,1)

26.0

In [114]:
def norm1(A):
    #вернуть макс столбцовую норму
    max = 0
    for i in range(A.shape[1]):
      cur = np.sum(np.abs(A[:,i]))
      if (cur > max):
        max = cur
    return max

In [115]:
norm1(A)

26

# ЗАДАНИЕ 2
домножить все элементы крайних строк и столбцов на -1 проверить что функция нормы не перестала работать

In [138]:
A = np.random.randint(10, size = (4,3))
A

array([[9, 6, 7],
       [3, 9, 4],
       [9, 0, 2],
       [5, 4, 6]])

In [139]:
norm1(A)

26

In [140]:
A[:,0] = A[:,0]*-1

In [141]:
A[:,A.shape[1] - 1] = A[:,A.shape[1] - 1] *-1

In [142]:
A

array([[-9,  6, -7],
       [-3,  9, -4],
       [-9,  0, -2],
       [-5,  4, -6]])

In [143]:
norm1(A)

26

it didnt change

# ЗАДАНИЕ 3

проверить что спектральная норма соответствует определению АТ А ** 0,5

In [85]:
A = np.random.randint(10, size = (4,3))

In [86]:
A

array([[7, 0, 0],
       [0, 5, 6],
       [1, 9, 3],
       [8, 0, 9]])

In [87]:
la.norm(A,2)


14.735456564773022

In [97]:
np.max(la.eigvals(A.T@A)**0.5)

14.73545656477302

In [102]:
np.isclose(np.max(la.eigvals(A.T@A)**0.5), la.norm(A,2), rtol=1e-05, atol=1e-08, equal_nan=False)

True