In [1]:
import numpy as np

In [2]:
import numpy.linalg as la

In [3]:
import scipy.linalg as sla

In [4]:
n = 3
X = np.random.rand(n)
X0 = X/la.norm(X)
X = X0.reshape(n,1)
X

array([[0.26977125],
       [0.44411544],
       [0.85439157]])

In [5]:
A = np.random.rand(n,n)
A

array([[0.95830252, 0.37852151, 0.9712671 ],
       [0.75042327, 0.51620988, 0.95605902],
       [0.31294711, 0.45534446, 0.80354103]])

In [6]:
E = np.eye(n)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
b = np.random.rand(n).reshape(n,1)
b
#b[1:]

array([[0.27770956],
       [0.55211943],
       [0.77300726]])

In [25]:
def MetodQR(A0,b0):
    n = A0.shape[0]
    A = A0.copy() 
    #b0 = b0.reshape(n,1)  
    b = b0.copy()
    E = np.eye(n)
    
    x = b*0

    Q = E.copy()
    
    for i in range(n-1):   
      a1 = A[i:,i]
      e1 = E[i:,i]          
      if (not ((a1 == a1@e1).all())):#
        X = (a1 - la.norm(a1)*e1)/la.norm((a1 - la.norm(a1)*e1))
        X = X.reshape(n-i,1)
        #print('NORM X',la.norm(X))
        U_tmp = E[i:,i:] - 2*X@X.T  
        U = E.copy()
        U[i:,i:] = U_tmp.copy()                
       # A = U@A
        A[i:,i:] = U[i:,i:]@A[i:,i:]
        #b = U@b
        b[i:,0] = U[i:,i:]@b[i:,0]
        #print('print 1',(la.norm(A[i:,i])))
        #print('print 2', A )

        ### QR method
        Q = Q@U.T

      else:
        print("ELSE")
        continue
    
    R = A.copy()
    print('QR',Q@R) #equals A0
    """
        # obratnyi hod
        for k in reversed(range(n)):
          sum = 0
          for i in range(k,n):
            sum += A[k,i]*x[i,0]
          x[k,0] = (b[k,0] - sum)/A[k,k]
        #print(x)
    """
      
    return [Q,R]


In [26]:
MetodQR(A,b)

QR [[0.95830252 0.37852151 0.9712671 ]
 [0.75042327 0.51620988 0.95605902]
 [0.31294711 0.45534446 0.80354103]]


[array([[ 0.7625258 , -0.4859003 ,  0.42714786],
        [ 0.59711531,  0.27445063, -0.75374409],
        [ 0.24901348,  0.82980585,  0.4994142 ]]),
 array([[ 1.25674767e+00,  7.10256149e-01,  1.51158624e+00],
        [ 3.59509069e-17,  3.35597907e-01,  4.57235070e-01],
        [ 3.72636550e-17, -8.83113872e-18,  9.55506258e-02]])]

In [27]:
la.qr(A)#the same as mine

(array([[-0.7625258 ,  0.4859003 ,  0.42714786],
        [-0.59711531, -0.27445063, -0.75374409],
        [-0.24901348, -0.82980585,  0.4994142 ]]),
 array([[-1.25674767, -0.71025615, -1.51158624],
        [ 0.        , -0.33559791, -0.45723507],
        [ 0.        ,  0.        ,  0.09555063]]))