In [ ]:
import numpy as np

In [ ]:
import numpy.linalg as la

In [ ]:
import scipy.linalg as sla

In [ ]:
n = 1000

In [ ]:
#X = np.array([[0.1**0.5, 0.3**0.5, 0.6**0.5]])
X = np.random.rand(n)
X0 = X/la.norm(X)
X = X0.reshape(n,1)
X

array([[4.92827501e-02],
       [7.25243965e-03],
       [5.10475369e-02],
       [4.74458305e-02],
       [3.58663995e-02],
       [2.76827303e-02],
       [2.61899979e-03],
       [7.39545004e-03],
       [3.54070125e-03],
       [2.76590235e-02],
       [2.62132672e-02],
       [3.72423634e-03],
       [2.80169641e-02],
       [9.20490511e-03],
       [5.04637318e-02],
       [4.31967285e-02],
       [1.03614257e-02],
       [3.51510954e-02],
       [2.95397600e-03],
       [3.89765572e-02],
       [1.77270893e-02],
       [6.81435300e-03],
       [2.11896088e-02],
       [4.22937269e-02],
       [3.50735620e-02],
       [4.86511575e-02],
       [1.76705740e-02],
       [5.03872771e-02],
       [3.91194664e-02],
       [2.78546631e-02],
       [3.92026215e-02],
       [4.81490645e-02],
       [4.39039354e-02],
       [2.45687831e-02],
       [3.69439317e-03],
       [1.84379555e-02],
       [3.10956412e-02],
       [7.10887929e-03],
       [3.16071210e-03],
       [3.88294662e-02],


In [ ]:
la.norm(X)

0.9999999999999999

# Построить матрицу отражений и проверить ее свойства


In [ ]:
E = np.eye(n)

In [ ]:
E

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
U = E - 2*X@X.T

In [ ]:
U

array([[ 9.95142421e-01, -7.14840343e-04, -5.03152601e-03, ...,
        -2.34885491e-03, -5.37505845e-03, -4.14299764e-03],
       [-7.14840343e-04,  9.99894804e-01, -7.40438362e-04, ...,
        -3.45657020e-04, -7.90992527e-04, -6.09682704e-04],
       [-5.03152601e-03, -7.40438362e-04,  9.94788298e-01, ...,
        -2.43296605e-03, -5.56753619e-03, -4.29135599e-03],
       ...,
       [-2.34885491e-03, -3.45657020e-04, -2.43296605e-03, ...,
         9.98864224e-01, -2.59907923e-03, -2.00332316e-03],
       [-5.37505845e-03, -7.90992527e-04, -5.56753619e-03, ...,
        -2.59907923e-03,  9.94052335e-01, -4.58435259e-03],
       [-4.14299764e-03, -6.09682704e-04, -4.29135599e-03, ...,
        -2.00332316e-03, -4.58435259e-03,  9.96466464e-01]])

In [ ]:
U0=U.copy()

In [ ]:
#symmetric?

In [ ]:
U==U.T 
#yes

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [ ]:
#ortogonal?
U = U0.copy()
U@U.T
#yes

array([[ 1.00000000e+00,  5.42101086e-19, -7.37257477e-18, ...,
        -1.30104261e-18,  5.20417043e-18, -4.33680869e-19],
       [ 5.42101086e-19,  1.00000000e+00, -3.25260652e-19, ...,
        -1.08420217e-19,  1.08420217e-19, -6.50521303e-19],
       [-7.37257477e-18, -3.25260652e-19,  1.00000000e+00, ...,
        -1.08420217e-18,  8.67361738e-19,  4.33680869e-19],
       ...,
       [-1.30104261e-18, -1.08420217e-19, -1.08420217e-18, ...,
         1.00000000e+00, -8.67361738e-19, -8.67361738e-19],
       [ 5.20417043e-18,  1.08420217e-19,  8.67361738e-19, ...,
        -8.67361738e-19,  1.00000000e+00, -8.67361738e-19],
       [-4.33680869e-19, -6.50521303e-19,  4.33680869e-19, ...,
        -8.67361738e-19, -8.67361738e-19,  1.00000000e+00]])

In [ ]:
#sobstv
#la.eig(U)

![%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png](attachment:%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5.png)

# Пункт 2, Постройте оптимизированную процедуру для домножения Aна U (x ) слева: (E−2 x xT ) Ai
без вычисления матрицы x xT

In [ ]:
A = np.random.rand(n,n)

In [ ]:
A

array([[0.16339381, 0.46288185, 0.66469111, ..., 0.99449472, 0.59328635,
        0.03249399],
       [0.40115357, 0.86506468, 0.36874135, ..., 0.84830031, 0.41861235,
        0.9693876 ],
       [0.10384796, 0.37108216, 0.04521319, ..., 0.86734936, 0.88640699,
        0.49200965],
       ...,
       [0.68412151, 0.43630274, 0.96491915, ..., 0.7226276 , 0.19044271,
        0.48655881],
       [0.59466365, 0.40123758, 0.2569541 , ..., 0.5982424 , 0.31444467,
        0.55477911],
       [0.87339124, 0.82257153, 0.42606728, ..., 0.21215115, 0.50003073,
        0.33067252]])

In [ ]:
%timeit U@A

10 loops, best of 5: 56.1 ms per loop


In [ ]:
U@A

array([[-1.2231016 , -0.95480846, -0.68294595, ..., -0.38977782,
        -0.73555141, -1.3157343 ],
       [ 0.19711718,  0.65643765,  0.17042335, ...,  0.64459104,
         0.22306085,  0.77098259],
       [-1.33229706, -1.09737483, -1.35068197, ..., -0.56649317,
        -0.49001568, -0.90449791],
       ...,
       [ 0.01368946, -0.24921342,  0.31327685, ...,  0.05327042,
        -0.4521093 , -0.16536938],
       [-0.93953559, -1.16747976, -1.23424719, ..., -0.93349716,
        -1.15595462, -0.93707639],
       [-0.30914173, -0.38656736, -0.72332365, ..., -0.96848594,
        -0.6333264 , -0.81922267]])

In [ ]:
#now new method
from numba import jit


In [ ]:
def multiplyMatrixesOld1(U,A):
    for i in range(n):
        for j in range(n):
            XXT[i,j] = X[i]*X[j] 
    
    #for i in range(n):
   #     for j in range(n):
     #       sum = XXT[i,j]*A[j,i]
    res = A - 2*XXT@A
    return res

In [ ]:
def multiplyMatrixesOld2(U,A):
    XXT = 0*np.eye(n)
    for i in range(n):
        XXT[i,:] = (X[i]*X).reshape(1,n)
    res = A - 2*XXT@A
    return res

In [ ]:
def multiplyMatrixesAfter(U,A):
    #U = E - 2*X@X.T
    #U@A = A -2*X@X.T@A 
    res = A -2*X@(X.T@A)
    return res

In [ ]:
multiplyMatrixesAfter(U,A)

array([[-1.2231016 , -0.95480846, -0.68294595, ..., -0.38977782,
        -0.73555141, -1.3157343 ],
       [ 0.19711718,  0.65643765,  0.17042335, ...,  0.64459104,
         0.22306085,  0.77098259],
       [-1.33229706, -1.09737483, -1.35068197, ..., -0.56649317,
        -0.49001568, -0.90449791],
       ...,
       [ 0.01368946, -0.24921342,  0.31327685, ...,  0.05327042,
        -0.4521093 , -0.16536938],
       [-0.93953559, -1.16747976, -1.23424719, ..., -0.93349716,
        -1.15595462, -0.93707639],
       [-0.30914173, -0.38656736, -0.72332365, ..., -0.96848594,
        -0.6333264 , -0.81922267]])

In [ ]:
X.T@A


array([[14.06674151, 14.38323053, 13.67250262, 13.61438164, 13.78891672,
        13.96011982, 13.72259   , 13.5548342 , 13.9768722 , 13.65952637,
        13.60245966, 13.28644074, 14.37553502, 13.93959424, 13.31638016,
        13.64815782, 13.16188169, 13.79912292, 13.31291654, 14.07854861,
        13.75440082, 13.49754972, 13.54430118, 13.18979065, 13.72138399,
        13.68165917, 13.73498317, 13.75459767, 13.90083646, 13.52741839,
        13.93186269, 13.90396841, 13.61597906, 13.20767497, 14.24624959,
        13.08154126, 13.66625697, 13.58031729, 13.83201222, 14.03738464,
        13.84400201, 13.51607212, 13.45658495, 13.66112012, 13.96200417,
        13.57898343, 13.57989395, 13.78665929, 13.35491484, 13.90784624,
        14.25978796, 13.58759366, 13.87877322, 13.63752669, 13.85482705,
        13.99541231, 13.27441775, 14.18584829, 14.16515794, 14.28229892,
        13.88271897, 13.7468816 , 13.76232521, 13.67347015, 13.89591941,
        13.55218355, 13.91875745, 13.64078551, 14.1

In [ ]:
%timeit multiplyMatrixesAfter(U,A)

100 loops, best of 5: 6.54 ms per loop


In [ ]:
A

array([[0.16339381, 0.46288185, 0.66469111, ..., 0.99449472, 0.59328635,
        0.03249399],
       [0.40115357, 0.86506468, 0.36874135, ..., 0.84830031, 0.41861235,
        0.9693876 ],
       [0.10384796, 0.37108216, 0.04521319, ..., 0.86734936, 0.88640699,
        0.49200965],
       ...,
       [0.68412151, 0.43630274, 0.96491915, ..., 0.7226276 , 0.19044271,
        0.48655881],
       [0.59466365, 0.40123758, 0.2569541 , ..., 0.5982424 , 0.31444467,
        0.55477911],
       [0.87339124, 0.82257153, 0.42606728, ..., 0.21215115, 0.50003073,
        0.33067252]])

In [ ]:
res = X.T@A
res

array([[14.06674151, 14.38323053, 13.67250262, 13.61438164, 13.78891672,
        13.96011982, 13.72259   , 13.5548342 , 13.9768722 , 13.65952637,
        13.60245966, 13.28644074, 14.37553502, 13.93959424, 13.31638016,
        13.64815782, 13.16188169, 13.79912292, 13.31291654, 14.07854861,
        13.75440082, 13.49754972, 13.54430118, 13.18979065, 13.72138399,
        13.68165917, 13.73498317, 13.75459767, 13.90083646, 13.52741839,
        13.93186269, 13.90396841, 13.61597906, 13.20767497, 14.24624959,
        13.08154126, 13.66625697, 13.58031729, 13.83201222, 14.03738464,
        13.84400201, 13.51607212, 13.45658495, 13.66112012, 13.96200417,
        13.57898343, 13.57989395, 13.78665929, 13.35491484, 13.90784624,
        14.25978796, 13.58759366, 13.87877322, 13.63752669, 13.85482705,
        13.99541231, 13.27441775, 14.18584829, 14.16515794, 14.28229892,
        13.88271897, 13.7468816 , 13.76232521, 13.67347015, 13.89591941,
        13.55218355, 13.91875745, 13.64078551, 14.1

In [ ]:
def multiplyMatrixesBest(U,A):
    #U = E - 2*X@X.T
    #U@A = A -2*X@X.T@A     
    XTA = X.T*0
    for i in range(n):
      XTA[:,i] = X.T@A[:,i]
    res = A - 2*X*XTA
    return res

In [ ]:
multiplyMatrixesBest(U,A)

array([[-1.2231016 , -0.95480846, -0.68294595, ..., -0.38977782,
        -0.73555141, -1.3157343 ],
       [ 0.19711718,  0.65643765,  0.17042335, ...,  0.64459104,
         0.22306085,  0.77098259],
       [-1.33229706, -1.09737483, -1.35068197, ..., -0.56649317,
        -0.49001568, -0.90449791],
       ...,
       [ 0.01368946, -0.24921342,  0.31327685, ...,  0.05327042,
        -0.4521093 , -0.16536938],
       [-0.93953559, -1.16747976, -1.23424719, ..., -0.93349716,
        -1.15595462, -0.93707639],
       [-0.30914173, -0.38656736, -0.72332365, ..., -0.96848594,
        -0.6333264 , -0.81922267]])

In [ ]:
np.array([[1],[2],[3]])@np.array([[1,2,3]])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
%timeit multiplyMatrixesBest(U,A)

KeyboardInterrupt: ignored

In [ ]:
def ref(A,X):
  res = A*0
  res = A-2*X*(X.T@A)
  return res

In [ ]:
ref(A,X)

In [ ]:
%timeit ref(A,X)

# Пункт 3, Реализуйте метод отражений: на i−ом шаге метода i−й столбец должен будет после преобразования отражения принять вид c нулями под главной диагональю:

In [ ]:
n = 3
X = np.random.rand(n)
X0 = X/la.norm(X)
X = X0.reshape(n,1)
X

array([[0.82207381],
       [0.56927955],
       [0.01074502]])

In [ ]:
A = np.random.rand(n,n)
A

array([[0.07121611, 0.85049278, 0.08814037],
       [0.92079415, 0.6499966 , 0.20746705],
       [0.34602088, 0.75862571, 0.39029353]])

In [ ]:
E = np.eye(n)
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
b = np.random.rand(n).reshape(n,1)
b
#b[1:]

array([[0.11699987],
       [0.45601033],
       [0.58855838]])

In [ ]:
def MetodOtrazheniy(A0,b0):
    n = A0.shape[0]
    A = A0.copy() 
    #b0 = b0.reshape(n,1)  
    b = b0.copy()
    E = np.eye(n)
    x = b*0
    
    for i in range(n-1):   
      a1 = A[i:,i]#perhaps A
      e1 = E[i:,i]          
      if (not ((a1 == a1@e1).all())):
        X = (a1 - la.norm(a1)*e1)/la.norm((a1 - la.norm(a1)*e1))
        X = X.reshape(n-i,1)
        U = E[i:,i:] - 2*X@X.T      
        A_tmp = U@A[i:,i:] 
        A[i:,i:] = 0
        A[i:,i:] = A_tmp
        b_tmp = U@b0[i:]
        b[i:] = b_tmp
        print('print 1',U)
        print('print 2', A_tmp )
      else:
        print("ELSE")
        continue

    # obratnyi hod
    x[n-1] = b[n-1]
    for i in reversed(range(n-1)):
      sum = 0
      for j in range(i+1,n):
        sum += A[i,j]*x[j]
      x[i] = b[i] - sum
    
    print(x)  

    return [A,b]


In [ ]:
MetodOtrazheniy(A,b)

print 1 [[ 0.07220992  0.93364359  0.35084951]
 [ 0.93364359  0.06046597 -0.35306305]
 [ 0.35084951 -0.35306305  0.86732411]]
print 2 [[ 9.86237317e-01  9.34442625e-01  3.36999186e-01]
 [-4.39091600e-17  5.65517106e-01 -4.29618356e-02]
 [-2.49667147e-17  7.26879556e-01  2.96186044e-01]]
print 1 [[ 0.61405315  0.78926468]
 [ 0.78926468 -0.61405315]]
print 2 [[ 9.20957918e-01  2.07388333e-01]
 [ 3.80550888e-16 -2.15782231e-01]]
[[-0.0548237 ]
 [ 0.74485261]
 [-0.00149327]]


[array([[ 9.86237317e-01,  9.34442625e-01,  3.36999186e-01],
        [-4.39091600e-17,  9.20957918e-01,  2.07388333e-01],
        [-2.49667147e-17,  3.80550888e-16, -2.15782231e-01]]),
 array([[ 0.64069509],
        [ 0.74454292],
        [-0.00149327]])]

In [ ]:
?sla.solve_triangular 

In [ ]:
x = sla.solve_triangular(MetodOtrazheniy(A,b)[0], MetodOtrazheniy(A,b)[1], lower=False)
x

print 1 [[ 0.07220992  0.93364359  0.35084951]
 [ 0.93364359  0.06046597 -0.35306305]
 [ 0.35084951 -0.35306305  0.86732411]]
print 2 [[ 9.86237317e-01  9.34442625e-01  3.36999186e-01]
 [-4.39091600e-17  5.65517106e-01 -4.29618356e-02]
 [-2.49667147e-17  7.26879556e-01  2.96186044e-01]]
print 1 [[ 0.61405315  0.78926468]
 [ 0.78926468 -0.61405315]]
print 2 [[ 9.20957918e-01  2.07388333e-01]
 [ 3.80550888e-16 -2.15782231e-01]]
[[-0.0548237 ]
 [ 0.74485261]
 [-0.00149327]]
print 1 [[ 0.07220992  0.93364359  0.35084951]
 [ 0.93364359  0.06046597 -0.35306305]
 [ 0.35084951 -0.35306305  0.86732411]]
print 2 [[ 9.86237317e-01  9.34442625e-01  3.36999186e-01]
 [-4.39091600e-17  5.65517106e-01 -4.29618356e-02]
 [-2.49667147e-17  7.26879556e-01  2.96186044e-01]]
print 1 [[ 0.61405315  0.78926468]
 [ 0.78926468 -0.61405315]]
print 2 [[ 9.20957918e-01  2.07388333e-01]
 [ 3.80550888e-16 -2.15782231e-01]]
[[-0.0548237 ]
 [ 0.74485261]
 [-0.00149327]]


array([[-0.11723891],
       [ 0.80688565],
       [ 0.00692028]])

In [ ]:
def MetodOtrazheniy2(A0,b0):
    n = A0.shape[0]
    A = A0.copy() 
    #b0 = b0.reshape(n,1)  
    b = b0.copy()
    E = np.eye(n)
    
    x = b*0
    
    for i in range(n-1):   
      a1 = A[i:,i]
      e1 = E[i:,i]          
      if (not ((a1 == a1@e1).all())):#
        X = (a1 - la.norm(a1)*e1)/la.norm((a1 - la.norm(a1)*e1))
        X = X.reshape(n-i,1)
        print('NORM X',la.norm(X))
        U_tmp = E[i:,i:] - 2*X@X.T  
        U = E.copy()
        U[i:,i:] = U_tmp.copy()                
       # A = U@A
        A[i:,i:] = U[i:,i:]@A[i:,i:]
        #b = U@b
        b[i:,0] = U[i:,i:]@b[i:,0]
        print('print 1',(la.norm(A[i:,i])))
        #print('print 2', b_tmp )
      else:
        print("ELSE")
        continue

    # obratnyi hod
    for k in reversed(range(n)):
      sum = 0
      for i in range(k,n):
        sum += A[k,i]*x[i,0]
      x[k,0] = (b[k,0] - sum)/A[k,k]
    print(x)

      
    return [A,b]


In [ ]:
MetodOtrazheniy2(A,b)

NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]


[array([[ 9.86237317e-01,  9.34442625e-01,  3.36999186e-01],
        [-4.39091600e-17,  9.20957918e-01,  2.07388333e-01],
        [-2.49667147e-17,  3.80550888e-16, -2.15782231e-01]]),
 array([[ 0.64069509],
        [ 0.26463253],
        [-0.29582897]])]

In [ ]:
 b

array([[0.11699987],
       [0.45601033],
       [0.58855838]])

In [ ]:
sla.solve_triangular(MetodOtrazheniy2(A,b)[0],MetodOtrazheniy2(A,b)[1], lower=False)
# check reverse hod

print 1 0.9862373173082939
print 1 0.9209579180802993
[[-0.64824216]
 [ 0.80688565]
 [ 0.00692028]]
print 1 0.9862373173082939
print 1 0.9209579180802993
[[-0.64824216]
 [ 0.80688565]
 [ 0.00692028]]


array([[-0.64824216],
       [ 0.80688565],
       [ 0.00692028]])

In [ ]:
sla.solve(A,b)

array([[ 0.20143169],
       [-0.02137854],
       [ 1.37096077]])

In [36]:
%timeit sla.solve(A,b)

The slowest run took 47.27 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 32.3 µs per loop


In [37]:
%timeit MetodOtrazheniy2(A,b)

NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NORM X 0.9999999999999999
print 1 0.9209579180802993
[[ 0.20143169]
 [-0.02137854]
 [ 1.37096077]]
NORM X 1.0
print 1 0.9862373173082939
NOR

In [ ]:
A@sla.solve(A,b)

array([[0.11699987],
       [0.45601033],
       [0.58855838]])

In [ ]:
x = sla.solve_triangular(MetodOtrazheniy2(A,b)[0], MetodOtrazheniy2(A,b)[1], lower=False)
x

print 1 0.9862373173082939
print 1 0.9209579180802993
[[-0.64824216]
 [ 0.80688565]
 [ 0.00692028]]
print 1 0.9862373173082939
print 1 0.9209579180802993
[[-0.64824216]
 [ 0.80688565]
 [ 0.00692028]]


array([[-0.64824216],
       [ 0.80688565],
       [ 0.00692028]])

In [ ]:
np.array([[1,0,0],[0,2,3],[0,2,3]])@np.array([[1,2,3],[1,2,3],[1,2,3]])

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [ 5, 10, 15]])

In [ ]:
np.array([[2,3],[2,3]])@np.array([[2,3],[2,3]])

array([[10, 15],
       [10, 15]])

# SLA solve test section

In [ ]:
testX = np.random.rand(n).reshape(n,1)
testX

array([[0.11764401],
       [0.07559186],
       [0.15342394]])

In [ ]:
testA = np.random.rand(n,n)
testA

array([[0.4597253 , 0.9848175 , 0.23246728],
       [0.395427  , 0.11387544, 0.39854992],
       [0.03388562, 0.62198184, 0.74691874]])

In [ ]:
testB = testA@testX
testB

array([[0.16419416],
       [0.11627477],
       [0.16559842]])

In [ ]:
sla.solve(testA, testB)

array([[0.11764401],
       [0.07559186],
       [0.15342394]])

In [ ]:
#correct

1 чтобы вычисления производились быстрее можно повторные вычисления замениь сохранением в переменную (чтобы число заново не считать)
и заменить векторы столбцы на одномерный массив
2 @ подгоняет размеры, .dot перемножает чисто по столбцам строго
3 вержбицкий проще, так как больше описано словами, чем формулами (как у Богачева)