In [1]:
import numpy as np
import numpy.linalg as la
import scipy.linalg as sla

In [2]:
n=5
A0=np.random.rand(n,n)-0.5
A=A0.copy()
la.cond(A)

11.027742769007892

In [ ]:
A2 = A.T @ A 

In [ ]:
la.cond(A2)

1507.6096556621799

In [ ]:
A

array([[ 0.33548485,  0.42206317, -0.10375539, -0.29550528,  0.37261741],
       [-0.1235811 , -0.21418126,  0.23829906,  0.49732964,  0.48455009],
       [ 0.43054981,  0.18273637, -0.08275874,  0.09553632,  0.32398833],
       [ 0.23550755, -0.36501968, -0.38076547,  0.47484862, -0.09579366],
       [-0.0973027 ,  0.08807694, -0.27520649, -0.40158709,  0.44200863]])

In [ ]:
# A[0,0] -> max по столбцу (по модулю)
D=np.diag(np.concatenate( ([1/A[0,0]],np.ones(n-1)) ))

In [ ]:
D@A

array([[ 1.        ,  1.25806926, -0.30926998, -0.88083047,  1.11068328],
       [-0.1235811 , -0.21418126,  0.23829906,  0.49732964,  0.48455009],
       [ 0.43054981,  0.18273637, -0.08275874,  0.09553632,  0.32398833],
       [ 0.23550755, -0.36501968, -0.38076547,  0.47484862, -0.09579366],
       [-0.0973027 ,  0.08807694, -0.27520649, -0.40158709,  0.44200863]])

In [ ]:
#%timeit A[0,:]/=A[0,0]

In [ ]:
#kf=A[0,0]
#%timeit for i in range(n): A[0,i]*=kf

$ x^2=\int_1^2 f(x) dx $


In [ ]:
from numba import jit

In [ ]:
#@jit
def test(A0, b0):
    #global n
    A=A0.copy()
    b=b0.copy()
    n = A.shape[0]
#    print(A@x0 - b)
    for k in range(n): # k=0..n-1
        # выбор главного элемента - TODO
        b[k]/=A[k,k]
        A[k,k:]/=A[k,k]
        for i in range(k+1,n):    
            b[i] -= A[i,k]*b[k]
            A[i,:] -= A[i,k]*A[k,:]
    #    for j in range(0,n):
    #        A[i,j] -= A[i,0]*A[0,j]
    #A[1:,:] -= A[0,:]*A[1:,0:1]
#    print('after Gauss:', A .dot(x0) - b)
    x=np.zeros(n)
    x[-1] = b[-1]
    #x[n-k] = b[n-k]-   A[n-k,n-1]*x[n-1]-A[n-k,n-2]*x[n-2]-A[n-k,n-3]*x[n-3]-...A[n-k,n-k]*x[n-k]
    for k in range(n-2,-1,-1):
        x[k] = b[k]-np.sum(x[k+1:]*A[k,k+1:])
#    print('check obr. hod:', A .dot(x) - b)
#    print(x-x0)
    return x


x0 = np.ones(n) 
b= A.dot(x0)
#print(A.dot(x0)-b)
#np.max(np.abs(np.tril(test(),-1)))
xx=test(A,b)
la.norm(A.dot(xx)-b)/la.norm(b)

7.424070842418325e-16

In [ ]:
#C = A*B
#c_ij = a_ij * b_ij
#a_i(,j которого нет) * b_ij

In [ ]:
%timeit test()

4.04 µs ± 145 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
4/3*n**3 / 4.5e-6 / 1e9

0.037037037037037035

In [ ]:
np.tril(test(),-1)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
A1=test()
A1

array([[  1.        ,   1.25806926,  -0.30926998,  -0.88083047,
          1.11068328],
       [  0.        ,   1.        ,  -3.40805738,  -6.61711825,
        -10.5916223 ],
       [  0.        ,   0.        ,   1.        ,   1.62023142,
          3.37285171],
       [  0.        ,   0.        ,   0.        ,   1.        ,
          2.79834705],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          1.        ]])

In [ ]:
n=1000
A=np.random.rand(n,n)-0.5
x0 = np.ones(n) 

b= A.dot(x0)
#print(A.dot(x0)-b)
#np.max(np.abs(np.tril(test(),-1)))
xx=test(A,b)
la.norm(A.dot(xx)-b)/la.norm(b)

8.368448097338723e-12