In [1]:
import numpy as np
import numpy.linalg as la

In [2]:
n = 5

In [3]:
A = np.random.rand(n,n)
A

array([[0.5626209 , 0.10591968, 0.99861373, 0.21648771, 0.35941308],
       [0.03401601, 0.51285169, 0.1565215 , 0.76227929, 0.69043836],
       [0.9021624 , 0.77665149, 0.1000903 , 0.0917888 , 0.4979654 ],
       [0.85354802, 0.13757228, 0.83766536, 0.87021548, 0.43485877],
       [0.00528582, 0.05344438, 0.19805708, 0.9095387 , 0.96976554]])

In [4]:
x = np.random.rand(n,1)
x

array([[0.36927042],
       [0.59253366],
       [0.97044271],
       [0.62564963],
       [0.80442843]])

In [5]:
b = A@x
b

array([[1.66418521],
       [1.50066614],
       [1.3484711 ],
       [2.10387523],
       [1.57498206]])

In [6]:
A0=A.copy()
b0 = b.copy()

In [7]:
A=A0.copy()
b=b0.copy()

# Метод Гаусса (обычный)

In [8]:
def beautyGauss(A,b):
  n = A.shape[0]
  t = A[:,:] * 0
  x = b*0
  print(x)
  for k in range(n-1):#n-1
    t[k+1:,k] = A[k+1:,k]/A[k,k]
    z = t[k+1:,k].shape[0]
    
    A[k+1:,k+1:] = A[k+1:,k+1:] - t[k+1:,k]*A[k,k+1:]
    print(A[k,k+1:])   
    A[k+1:,k] = A[k+1:,k] - A[k,k]*t[k+1:,k] #A[k+1:,k] = 0  
    b[k+1:,0] = b[k+1:,0]-t[k+1:,k]*b[k,0]
    
  x[n-1,0] = b[n-1,0]/A[n-1,n-1]
  for k in reversed(range(n-1)):
    x[k,0] = (b[k,0] - np.sum(A[k,k+1:]*x[k+1:,0]) )/A[k,k]
  print('A',A)
  print('b',b)
  print('Ax',A@x)
  return x

In [9]:
beautyGauss(A,b)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[0.10591968 0.99861373 0.21648771 0.35941308]
[-1.44475524  0.43384738  0.68706168]
[-0.34900821  0.43077224]
[-0.12373062]
A [[ 5.62620902e-01  1.05919684e-01  9.98613729e-01  2.16487712e-01
   3.59413082e-01]
 [ 0.00000000e+00  5.06447793e-01 -1.44475524e+00  4.33847377e-01
   6.87061678e-01]
 [ 0.00000000e+00  0.00000000e+00  6.96116562e-01 -3.49008211e-01
   4.30772236e-01]
 [-1.11022302e-16  0.00000000e+00  0.00000000e+00  1.14822071e+00
  -1.23730620e-01]
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16  2.22044605e-16
   5.39144188e-01]]
b [[ 1.66418521]
 [ 1.40004966]
 [-3.44936031]
 [ 6.32069727]
 [-1.17305665]]
Ax [[ 1.66418521]
 [ 1.40004966]
 [-3.44936031]
 [ 6.32069727]
 [-1.17305665]]


array([[ 4.32799572],
       [-1.55544853],
       [-0.96637945],
       [ 5.27031708],
       [-2.17577538]])

In [10]:
np.array([[1],[2],[3]])*np.array([1,2,3]).reshape(3,1)

array([[1],
       [4],
       [9]])

In [11]:
np.array([1,2,3])*np.array([1,2,3])

array([1, 4, 9])

In [12]:
def verzbitskyGauss(A,b):
  n = A.shape[0]
  t = A[:,:] * 0
  x = b*0
  
  for k in range(n-1):
    for i in range(k+1,n):
      t[i,k] = A[i,k]/A[k,k]
      b[i] = b[i] - t[i,k]*b[k]
      for j in range(k+1,n):
        A[i,j] = A[i,j] - t[i,k]*A[k,j]
        A[i,k] = 0;
    
  x[n-1,0] = b[n-1,0]/A[n-1,n-1]
  for k in reversed(range(n-1)):
    x[k,0] = (b[k,0] - np.sum(A[k,k+1:]*x[k+1:,0]) )/A[k,k]
  print('A',A)
  print('b',b)
  print('Ax',A@x)
  return x

In [13]:
A0

array([[0.5626209 , 0.10591968, 0.99861373, 0.21648771, 0.35941308],
       [0.03401601, 0.51285169, 0.1565215 , 0.76227929, 0.69043836],
       [0.9021624 , 0.77665149, 0.1000903 , 0.0917888 , 0.4979654 ],
       [0.85354802, 0.13757228, 0.83766536, 0.87021548, 0.43485877],
       [0.00528582, 0.05344438, 0.19805708, 0.9095387 , 0.96976554]])

In [14]:
beautyGauss(A,b)

[[ 0.]
 [ 0.]
 [-0.]
 [ 0.]
 [-0.]]
[0.10591968 0.99861373 0.21648771 0.35941308]
[-1.44475524  0.43384738  0.68706168]
[-0.34900821  0.43077224]
[-0.12373062]
A [[ 5.62620902e-01  1.05919684e-01  9.98613729e-01  2.16487712e-01
   3.59413082e-01]
 [ 0.00000000e+00  5.06447793e-01 -1.44475524e+00  4.33847377e-01
   6.87061678e-01]
 [ 0.00000000e+00  0.00000000e+00  6.96116562e-01 -3.49008211e-01
   4.30772236e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.14822071e+00
  -1.23730620e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  4.93038066e-32
   5.39144188e-01]]
b [[ 1.66418521]
 [ 1.40004966]
 [-3.44936031]
 [ 6.32069727]
 [-1.17305665]]
Ax [[ 1.66418521]
 [ 1.40004966]
 [-3.44936031]
 [ 6.32069727]
 [-1.17305665]]


array([[ 4.32799572],
       [-1.55544853],
       [-0.96637945],
       [ 5.27031708],
       [-2.17577538]])

# Метод Гаусса с постолбцовым выбором максимального (главного) элемента


то есть делим не на первую строку (у которой первый множитель может оказаться = 0), в оставшейся подсистеме, а на место первой - ставим строку с максимальным множителем (максимум выбирается по столбцу)

In [22]:
def GlavGauss(A,b): 
  Eps = 0.001
  n = A.shape[0]
  t = A[:,:] * 0
  x = b*0
  print(x)
 
  for k in range(n-1):
    #max el stolbec method begin
    st_el_max = 0
    max_idx = 0
    for idx in range(k,n):
      if (A[idx,k] > st_el_max):
        st_el_max = A[idx,k]
        max_idx = idx
    if (st_el_max < Eps):
      return 'Odnoznachnogo resheniya net'
    else:
      b[k], b[max_idx] = b[max_idx], b[k]
      A[k,k:], A[max_idx,k:] = A[max_idx,k:], A[k,k:]
    #max el stolbec method end
    
    t[k+1:,k] = A[k+1:,k]/A[k,k]
    z = t[k+1:,k].shape[0]
    
    A[k+1:,k+1:] = A[k+1:,k+1:] - t[k+1:,k]*A[k,k+1:]
    print(A[k,k+1:])   
    A[k+1:,k] = A[k+1:,k] - A[k,k]*t[k+1:,k] #A[k+1:,k] = 0  
    b[k+1:,0] = b[k+1:,0]-t[k+1:,k]*b[k,0]
    
  x[n-1,0] = b[n-1,0]/A[n-1,n-1]
  for k in reversed(range(n-1)):
    x[k,0] = (b[k,0] - np.sum(A[k,k+1:]*x[k+1:,0]) )/A[k,k]
  print('A',A)
  print('b',b)
  print('A@x',A@x)
  return x

In [23]:
GlavGauss(A,b)

[[ 0.]
 [ 0.]
 [-0.]
 [ 0.]
 [-0.]]
[0.10591968 0.99861373 0.21648771 0.35941308]
[-1.44475524  0.43384738  0.68706168]
[-0.34900821  0.43077224]
[-0.12373062]
A [[ 0.5626209   0.10591968  0.99861373  0.21648771  0.35941308]
 [ 0.          0.50644779 -1.44475524  0.43384738  0.68706168]
 [ 0.          0.          0.69611656 -0.34900821  0.43077224]
 [ 0.          0.          0.          1.14822071 -0.12373062]
 [ 0.          0.          0.          0.          0.53914419]]
b [[ 1.66418521]
 [ 1.40004966]
 [-3.44936031]
 [ 6.32069727]
 [-1.17305665]]
A@x [[ 1.66418521]
 [ 1.40004966]
 [-3.44936031]
 [ 6.32069727]
 [-1.17305665]]


array([[ 4.32799572],
       [-1.55544853],
       [-0.96637945],
       [ 5.27031708],
       [-2.17577538]])